/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 horse.gltf 
Author: Лапшин Сергей (https://sketchfab.com/serg111)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/horse-stl-ea54830dc4d444de809ee106ee5f55cd
Title: horse (stl)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/horse.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.horse_statue_01_horse_statue_01_0.geometry} material={materials.horse_statue_01} />
            <mesh geometry={nodes.horse_statue_01_horse_statue_01007_0.geometry} material={materials['horse_statue_01.007']} />
            <mesh geometry={nodes.horse_statue_01_horse_statue_01008_0.geometry} material={materials['horse_statue_01.008']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/horse.gltf')
